noise:
  min_snr_dB: 10
  max_snr_dB: 30
  noise_path: "dataset/sound-bible"
  prob: 0.4

speed:
  min_speed_rate: 0.9
  max_speed_rate: 1.1
  num_rates: 3
  prob: 0.0

volume:
  min_gain_dBFS: -15
  max_gain_dBFS: 15
  prob: 0.4

specaug:
  W: 0
  F: 10
  n_freq_masks: 2
  T: 50
  n_time_masks: 2
  p: 1.0
  adaptive_number_ratio: 0
  adaptive_size_ratio: 0
  max_n_time_masks: 20
  replace_with_zero: true
  prob: 0.3